- name: Download Node Exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.10.2/node_exporter-1.10.2.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes

- name: Copy Node Exporter Service File
  ansible.builtin.copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Start Node Exporter Service
  ansible.builtin.systemd_service:
    name: node_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes

